name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'phpunit.xml.dist'
      - 'phpstan.neon.dist'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'phpunit.xml.dist'
      - 'phpstan.neon.dist'

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        - 
          php-version: '8.1'
          summary: true
        - 
          php-version: '8.2'
        - 
          php-version: '8.3'
        - 
          php-version: '8.4'
        - 
          php-version: '8.5'
          summary: true

    steps:

      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit
        shell: bash
        run: |
          set -o pipefail

          vendor/bin/phpunit \
            --coverage-text \
            --coverage-clover coverage.xml \
            --log-junit junit.xml \
            2>&1 | tee phpunit-output.txt

      - name: PHPStan
        shell: bash
        run: |
          set -o pipefail

          vendor/bin/phpstan analyse \
            2>&1 | tee phpstan-output.txt

      - name: Upload junit
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: junit-${{ matrix.php-version }}
          path: junit.xml

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ matrix.php-version }}
          path: coverage.xml

      - name: Add summary
        if: always() && matrix.summary == true
        shell: bash
        run: |
          {
            echo "# 🧪 PHP ${{ matrix.php-version }}"
            echo

            echo "## PHPUnit + Coverage"
            echo
            echo '```text'
            cat phpunit-output.txt
            echo '```'
            echo

            echo "## PHPStan"
            echo
            echo '```text'
            cat phpstan-output.txt
            echo '```'
            echo
          } >> "$GITHUB_STEP_SUMMARY"
